<a href="https://colab.research.google.com/github/sailaja-37/ML-WORKSHOP/blob/main/Assignment1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version


Python 3.10.12


In [2]:
import numpy as np


#1. Perform arithmetic operations on NumPy arrays


In [15]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


#2. Write a script to compute the mean and standard deviation of a NumPy array.


In [4]:
a = np.array([1, 2, 3, 4, 5])

mean = np.mean(a)
sd = np.std(a)

print("Mean:", mean)
print("Standard Deviation:", sd)


Mean: 3.0
Standard Deviation: 1.4142135623730951


#3. Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [6]:

a = np.arange(10, 51, 5)
print("Array:", a)


Array: [10 15 20 25 30 35 40 45 50]


#4. Reshape the array into a 2x4 matrix.

In [12]:
a =np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_array = a.reshape(2, 4)
print("Reshaped Array:", reshaped_array)

Reshaped Array: [[1 2 3 4]
 [5 6 7 8]]


#5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
###• Extract the sub-matrix containing the last two rows and first two columns.
###• Replace all elements greater than 4 with 0.

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix = a[1:3, 0:2]
a[a > 4] = 0
print("last two rows and first two columns:")
print(sub_matrix)
print("replaced array:")
print(a)


last two rows and first two columns:
[[4 0]
 [0 0]]
replaced array:
[[1 2 3]
 [4 0 0]
 [0 0 0]]


#6. Create two 1D arrays:
###• a = np.array([1, 2, 3])
###• b = np.array([4, 5, 6])
###• Perform element-wise addition, multiplication, and division

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


#7. Create a random NumPy array of size (4, 4). Compute:
###• Mean of each column.
###• Maximum value of the entire array.
###• Sum of all elements.

In [22]:
arr = np.array([
    [1, 5, 15, 4],
    [8, 3, 6, 9],
    [7, 3, 9, 18],
    [3, 5, 6, 9]
])
column_mean = np.mean(arr, axis=0)
max_val= np.max(arr)
sum = np.sum(arr)
print("Array:", arr)
print("\nMean of Each Column:", column_mean)
print("Max Value in Array:", max_val)
print("Sum of All Elements:",sum)


Array: [[ 1  5 15  4]
 [ 8  3  6  9]
 [ 7  3  9 18]
 [ 3  5  6  9]]

Mean of Each Column: [ 4.75  4.    9.   10.  ]
Max Value in Array: 18
Sum of All Elements: 111


#8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [23]:

arr = np.array([1, 2, 3, 4])
modified_arr = (arr + 10) * 2

print("Original Array:", arr)
print("Modified Array:", modified_arr)


Original Array: [1 2 3 4]
Modified Array: [22 24 26 28]


#9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [24]:
arr = np.random.randint(1, 101, (3, 4, 5))
print("Original 3D Array:\n", arr)
second_layer = arr[1]
print("\n2D Array from First Dimension", second_layer)
b= arr[:, :2, -3:]
print("\nFirst Two Rows and Last Three Columns from Each Layer:\n",b)
arr[arr % 3 == 0] = -1
print("\nArray After Replacing :\n", arr)


Original 3D Array:
 [[[ 57  36  79  45  88]
  [ 57  94  73  12  28]
  [  2  33   3  78  65]
  [ 89   2  34  49  83]]

 [[ 29  67   9  89  49]
  [ 82  66  87  64  87]
  [ 79  40  81  16  83]
  [ 74  30 100  63  70]]

 [[  9  46  95   3  51]
  [ 58  97   7  35  69]
  [ 14  53  78  42   5]
  [ 44  33  82  27   5]]]

2D Array from First Dimension [[ 29  67   9  89  49]
 [ 82  66  87  64  87]
 [ 79  40  81  16  83]
 [ 74  30 100  63  70]]

First Two Rows and Last Three Columns from Each Layer:
 [[[79 45 88]
  [73 12 28]]

 [[ 9 89 49]
  [87 64 87]]

 [[95  3 51]
  [ 7 35 69]]]

Array After Replacing :
 [[[ -1  -1  79  -1  88]
  [ -1  94  73  -1  28]
  [  2  -1  -1  -1  65]
  [ 89   2  34  49  83]]

 [[ 29  67  -1  89  49]
  [ 82  -1  -1  64  -1]
  [ 79  40  -1  16  83]
  [ 74  -1 100  -1  70]]

 [[ -1  46  95  -1  -1]
  [ 58  97   7  35  -1]
  [ 14  53  -1  -1   5]
  [ 44  -1  82  -1   5]]]
